image: jhipster/jhipster:v5.5.0

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - .maven/
stages:
    - build
    - test
    - analyze
    - package
    - release
    - deploy


before_script:
    - export MAVEN_USER_HOME=`pwd`/.maven

    
deploy:staging:
    image: google/cloud-sdk
    stage: deploy
    environment:
      name: staging
    script:
      - echo "Deploy to staging target GAE instance with project ID $GCP_PROJECT_ID"
      - echo -n "$GCP_KEY" > /builds/canya-com/canexchange/key.json
      - echo -n "+ using GCP KEY for staging deployer " && cat /builds/canya-com/canexchange/key.json
      - gcloud auth activate-service-account --key-file /builds/canya-com/canexchange/key.json
      - gcloud config set project $GCP_PROJECT_ID
      - ./mvnw appengine:deploy -DskipTests -Pprod,prod-gae,no-liquibase 

    