# ===================================================================
# Spring Boot configuration for the "gae" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://google/canexchange?cloudSqlInstance=staging-can-work:australia-southeast1:canwork-staging&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
        username: canya
        password: 5Dy6ktTqgrQugDb
        hikari:
            maximumPoolSize: 8
