runtime: java
env: flex
health_check: 
  enable_health_check: True 
  check_interval_sec: 5 
  timeout_sec: 4 
  unhealthy_threshold: 2 
  healthy_threshold: 2
skip_files:
- ^(.*/)?\.bak$
- ^node_modules/(?!node\.js$).*
- ^build/(?!node\.js$).*
- ^bin/(?!node\.js$).*
handlers:
- url: /.*
  script: this field is required, but ignored